.test:linux:x64:
  stage: test
  tags: [x64, linux, docker]
  script:
    - 'cd /usr/local/lib && { curl -o libobjectbox.so -H "PRIVATE-TOKEN: $CI_API_TOKEN" "${OBXLIB_URL_Linux64}" ; ldconfig ; cd - ; }'
    - ./build/build.sh

# minimal supported Go version is 1.11.4
test:linux:x64:go1.11.4:
  extends: .test:linux:x64
  image: golang:1.11.4

test:linux:x64:go1.12:
  extends: .test:linux:x64
  image: golang:1.12

test:linux:x64:go1.13:
  extends: .test:linux:x64
  image: golang:1.13

test:linux:ARMv7hf:
  stage: test
  image: arm32v7/golang
  tags: [armv7hf, linux, docker]
  script:
    - 'cd /usr/local/lib && { curl -o libobjectbox.so -H "PRIVATE-TOKEN: $CI_API_TOKEN" "${OBXLIB_URL_LinuxARMv7hf}" ; ldconfig ; cd - ; }'
    - ./build/build.sh

test:mac:x64:
  stage: test
  tags: [x64, mac, go]
  script:
    - 'curl -o /usr/local/lib/libobjectbox.dylib -H "PRIVATE-TOKEN: $CI_API_TOKEN" "$OBXLIB_URL_Mac64"'
    - ./build/build.sh